export const programacaoGeral = [
  // --- QG do Frevo (Polo Lucas Cardoso) ---
  // Sábado
  {
    id: 1,
    dia: "Sábado",
    data: "14/02",
    palco: "QG do Frevo",
    artista: "Orq. Cônego Alexandre e Grupos Folcpopular e Papanguarte",
    horario: "20:00",
  },
  {
    id: 2,
    dia: "Sábado",
    data: "14/02",
    palco: "QG do Frevo",
    artista: "Vanessa da Mata",
    horario: "22:00",
  },
  {
    id: 3,
    dia: "Sábado",
    data: "14/02",
    palco: "QG do Frevo",
    artista: "Raí Saia Rodada",
    horario: "00:00",
  },
  // Domingo
  {
    id: 4,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Morganna Bernardo",
    horario: "10:00",
  },
  {
    id: 5,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Marron Brasileiro",
    horario: "12:00",
  },
  {
    id: 6,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "André Rio",
    horario: "14:00",
  },
  {
    id: 7,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Elba Ramalho",
    horario: "16:00",
  },
  {
    id: 8,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Ciel Santos",
    horario: "18:00",
  },
  {
    id: 9,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Nando Cordel",
    horario: "20:00",
  },
  {
    id: 10,
    dia: "Domingo",
    data: "15/02",
    palco: "QG do Frevo",
    artista: "Henrique Barbosa",
    horario: "22:00",
  },
  // Segunda
  {
    id: 11,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Maestro Forró",
    horario: "10:00",
  },
  {
    id: 12,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Almir Rouche",
    horario: "12:00",
  },
  {
    id: 13,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "André Marreta",
    horario: "14:00",
  },
  {
    id: 14,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Fundo de Quintal",
    horario: "16:00",
  },
  {
    id: 15,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Marcão Noventta",
    horario: "18:00",
  },
  {
    id: 16,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Priscila Senna",
    horario: "20:00",
  },
  {
    id: 17,
    dia: "Segunda",
    data: "16/02",
    palco: "QG do Frevo",
    artista: "Grupo Molejo",
    horario: "22:00",
  },
  // Terça
  {
    id: 18,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "100xtress",
    horario: "10:00",
  },
  {
    id: 19,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Clara Sobral",
    horario: "12:00",
  },
  {
    id: 20,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Geraldinho Lins",
    horario: "14:00",
  },
  {
    id: 21,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Bruninho Lima",
    horario: "16:00",
  },
  {
    id: 22,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Lady Falcão",
    horario: "18:00",
  },
  {
    id: 23,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Raphaela Santos",
    horario: "20:00",
  },
  {
    id: 24,
    dia: "Terça",
    data: "17/02",
    palco: "QG do Frevo",
    artista: "Edson Gomes",
    horario: "22:00",
  },

  // --- Palco Cultural (Polo Mestre J. Borges) ---
  // Sábado
  {
    id: 25,
    dia: "Sábado",
    data: "14/02",
    palco: "Palco Cultural",
    artista: "Bloco do Zé Pereira",
    horario: "19:00",
  },
  {
    id: 26,
    dia: "Sábado",
    data: "14/02",
    palco: "Palco Cultural",
    artista: "Elifas Jr.",
    horario: "20:00",
  },
  // Domingo
  {
    id: 27,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Anderson Alves",
    horario: "10:00",
  },
  {
    id: 28,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Spok Frevo",
    horario: "12:00",
  },
  {
    id: 29,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Gerlane Lops",
    horario: "14:00",
  },
  {
    id: 30,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Gustavo Travassos",
    horario: "16:00",
  },
  {
    id: 31,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Luizinho Moreno",
    horario: "18:00",
  },
  {
    id: 32,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Cultural",
    artista: "Irah Caldeira",
    horario: "20:00",
  },
  // Segunda
  {
    id: 33,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Dudu do Acordeon",
    horario: "10:00",
  },
  {
    id: 34,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Silvério Pessoa",
    horario: "12:00",
  },
  {
    id: 35,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Academia da Berlinda",
    horario: "14:00",
  },
  {
    id: 36,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Rodrigo Raposo",
    horario: "16:00",
  },
  {
    id: 37,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Silvana Salazar",
    horario: "18:00",
  },
  {
    id: 38,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Cultural",
    artista: "Cristina Amaral",
    horario: "20:00",
  },
  // Terça
  {
    id: 39,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Zé Barreto de Assis",
    horario: "10:00",
  },
  {
    id: 40,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Nena Queiroga",
    horario: "12:00",
  },
  {
    id: 41,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Mazamorra",
    horario: "14:00",
  },
  {
    id: 42,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Otto",
    horario: "16:00",
  },
  {
    id: 43,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Retrodac",
    horario: "18:00",
  },
  {
    id: 44,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Cultural",
    artista: "Ed Carlos",
    horario: "20:00",
  },

  // --- Palco Centenária (Polo Mestre Lula Vassoureiro) ---
  // Domingo
  {
    id: 45,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Concurso do Papangu - Categoria Adulto",
    horario: "09:00",
  },
  {
    id: 46,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Som Brasil",
    horario: "12:00",
  },
  {
    id: 47,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Victor Ferrari",
    horario: "14:00",
  },
  {
    id: 48,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Emerson Cavalcante",
    horario: "16:00",
  },
  {
    id: 49,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Amigas do Brega",
    horario: "18:00",
  },
  {
    id: 50,
    dia: "Domingo",
    data: "15/02",
    palco: "Palco Centenária",
    artista: "Faringes da Paixão",
    horario: "20:00",
  },
  // Segunda
  {
    id: 51,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "Amannda Leão",
    horario: "10:00",
  },
  {
    id: 52,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "Walter Lins",
    horario: "12:00",
  },
  {
    id: 53,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "Banda Pinguin",
    horario: "14:00",
  },
  {
    id: 54,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "Higor Henrique",
    horario: "16:00",
  },
  {
    id: 55,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "O Conde",
    horario: "18:00",
  },
  {
    id: 56,
    dia: "Segunda",
    data: "16/02",
    palco: "Palco Centenária",
    artista: "Mega Play",
    horario: "20:00",
  },
  // Terça
  {
    id: 57,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Concurso do Papangu - Categoria Infantil",
    horario: "09:00",
  },
  {
    id: 58,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Michel Diniz",
    horario: "10:00",
  },
  {
    id: 59,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Douglas Leon",
    horario: "12:00",
  },
  {
    id: 60,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Roginho",
    horario: "14:00",
  },
  {
    id: 61,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Elvis Viana",
    horario: "16:00",
  },
  {
    id: 62,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "Benil",
    horario: "18:00",
  },
  {
    id: 63,
    dia: "Terça",
    data: "17/02",
    palco: "Palco Centenária",
    artista: "O Pelotão",
    horario: "20:00",
  },
];
